import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Provider as JotaiProvider } from "jotai";
import { JotaiHydrator } from "@/lib/jotai/JotaiHydrator";
import { env } from "@/env";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body suppressHydrationWarning={process.env.NODE_ENV === "production"}>
        <JotaiProvider>
          <JotaiHydrator
            envVars={{
              AUTH_SECRET: env.AUTH_SECRET,
              DATABASE_URL: env.DATABASE_URL,
              NODE_ENV: env.NODE_ENV,
              REMOTE_LOGGER: env.REMOTE_LOGGER,
              DEBUG_LOGGER: env.DEBUG_LOGGER,
            }}
          >
            {children}
          </JotaiHydrator>
        </JotaiProvider>
      </body>
    </html>
  );
}
