// Auth Action Types - Safe for client component imports
// These types define application-specific interfaces for auth server actions

// =================================================================
// APPLICATION-SPECIFIC TYPES (not generated by Prisma)
// =================================================================

export interface SignInInput {
  email: string;
  password?: string;
  provider?: string;
}

// Session information (safe for client)
export interface SessionInfo {
  user: {
    id: string;
    name: string | null;
    email: string | null;
    image: string | null;
  } | null;
  isAuthenticated: boolean;
}

// Auth status result
export interface AuthStatusResult {
  isAuthenticated: boolean;
  user: SessionInfo["user"];
}
